[models]
default = "qwen:Qwen3-Coder-480B-A35B-Instruct"
recent = "qwen:Qwen3-Codex-480B-A35B-Instruct"

[models.providers.qwen]
class_path = "langchain_openai:ChatOpenAI"
base_url = "http://10.116.240.101:8030/openai"
api_key_env = "OPENAI_API_KEY"
models = [
  "Qwen3-Coder-480B-A35B-Instruct",
  "Qwen3-Codex-480B-A35B-Instruct",
  "EXAONE-4-32B",
  "Qwen3-A22B-Instruct-2507",
  "Llama-4-Scout",
]
